include:
  - '.gitlab-ci-files/common-prepare.yml'

# Pipeline-wide variables; Applies to all jobs.
variables:
  PEP_MACHINE_DIR: "/install/share/pEp"
  CARGO_HOME: /cargo
  CARGO_TARGET_DIR:

stages:
  - deps
  - build
  - test

# Debian

debian11:deps:
  extends: .make_in_docker
  stage: deps
  variables:
    MAKE_TARGET: "deps"
    CI_DISTRO_TARGET: "debian11"
    DEBIAN_FRONTEND: "noninteractive"
    BUILD: /build
  rules:
    - changes:
        - DEPENDENCIES
        - scripts/ci/debian11/deps.pEpEngine.debian11.Dockerfile
        - scripts/ci/common/build_pEpEngine_deps.sh

debian11:build:
  tags:
    - linux
  stage: build
  image: ${DOCKER_REGISTRY_HOST}/pep-debian11-engine-deps:${CI_COMMIT_REF_SLUG}
  script:
    - ./scripts/ci/common/prep_build.sh
    - make all
    - make db
    - make install
  variables:
    DEBUG: "maintainer"
    PKG_CONFIG_PATH: "$INSTPREFIX/share/pkgconfig/"
    LC_ALL: "en_US.UTF-8"
    CI_DISTRO_TARGET: "debian11"
    DEBIAN_FRONTEND: "noninteractive"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian11:tagged-build:
  tags:
    - linux
  stage: build
  image: ${DOCKER_REGISTRY_HOST}/pep-debian11-engine-deps:${CI_COMMIT_REF_SLUG}
  script:
    - ./scripts/ci/common/prep_build.sh
    - make all
    - make db
    - make install
  variables:
    DEBUG: "release"
    PKG_CONFIG_PATH: "$INSTPREFIX/share/pkgconfig/"
    LC_ALL: "en_US.UTF-8"
    CI_DISTRO_TARGET: "debian11"
    DEBIAN_FRONTEND: "noninteractive"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian11:test:
  tags:
    - linux
  image: ${DOCKER_REGISTRY_HOST}/pep-debian11-engine-deps:${CI_COMMIT_REF_SLUG}
  stage: test
  script:
    - ./scripts/ci/common/prep_build.sh
    - make dbinstall
    - LD_LIBRARY_PATH=/install/lib:$LD_LIBARY_PATH make test
  after_script:
    - cat local.conf
  variables:
    DEBUG: "maintainer"
    PKG_CONFIG_PATH: "$INSTPREFIX/share/pkgconfig/"
    LC_ALL: "en_US.UTF-8"
    CI_DISTRO_TARGET: "debian11"
    DEBIAN_FRONTEND: "noninteractive"
