include:
  - '.gitlab-ci-files/common-prepare.yml'

stages:
  - deps
  - build
  - build-docker
  - packages


# Debian

debian10:deps:
  extends: .make_in_docker
  stage: deps
  variables:
    MAKE_TARGET: "deps"
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"
  rules:
    - changes:
        - DEPENDENCIES
        - scripts/debian10/deps.pEpEngine.debian10.Dockerfile
        - scripts/common/build_pEpEngine_deps.sh

debian10:build:
  tags:
    - linux
  stage: build
  image: ${DOCKER_REGISTRY_HOST}/pep-debian10-engine-deps:latest
  script:
    - cd scripts/${CI_DISTRO_TARGET}
    - make ${MAKE_TARGET}
  variables:
    MAKE_TARGET: "build"
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian10:tagged-build:
  tags:
    - linux
  stage: build
  image: ${DOCKER_REGISTRY_HOST}/pep-debian10-engine-deps:latest
  script:
    - cd scripts/${CI_DISTRO_TARGET}
    - make ${MAKE_TARGET}
  variables:
    MAKE_TARGET: "build"
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian10:build-docker:
  extends: .make_in_docker
  stage: build-docker
  needs: ["debian10:build"]
  variables:
    MAKE_TARGET: "build-docker"
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian10:tagged-build-docker:
  extends: .make_in_docker
  stage: build-docker
  needs: ["debian10:tagged-build"]
  variables:
    MAKE_TARGET: "build-docker"
    CI_DISTRO_TARGET: "debian10"
    DEBIAN_FRONTEND: "noninteractive"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

# CentOS

centos8:deps:
  extends: .make_in_docker
  stage: deps
  variables:
    MAKE_TARGET: "deps"
    CI_DISTRO_TARGET: "centos8"
  rules:
    - changes:
        - DEPENDENCIES
        - scripts/centos8/deps.pEpEngine.centos8.Dockerfile
        - scripts/common/build_pEpEngine_deps.sh


centos8:build:
  tags:
    - linux
  stage: build
  image: ${DOCKER_REGISTRY_HOST}/pep-centos8-engine-deps:latest
  script:
    - cd scripts/${CI_DISTRO_TARGET}
    - make ${MAKE_TARGET}
  variables:
    MAKE_TARGET: "build"
    CI_DISTRO_TARGET: "centos8"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

centos8:tagged-build:
  tags:
    - linux
  stage: build
  image: ${DOCKER_REGISTRY_HOST}/pep-centos8-engine-deps:latest
  script:
    - cd scripts/${CI_DISTRO_TARGET}
    - make ${MAKE_TARGET}
  variables:
    MAKE_TARGET: "build"
    CI_DISTRO_TARGET: "centos8"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

centos8:build-docker:
  extends: .make_in_docker
  stage: build-docker
  needs: ["centos8:build"]
  variables:
    MAKE_TARGET: "build-docker"
    CI_DISTRO_TARGET: "centos8"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

centos8:tagged-build-docker:
  extends: .make_in_docker
  stage: build-docker
  needs: ["centos8:tagged-build"]
  variables:
    MAKE_TARGET: "build-docker"
    CI_DISTRO_TARGET: "centos8"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

centos8:rpm:
  extends: .make_in_docker
  stage: packages
  needs: ["centos8:build-docker"]
  variables:
    MAKE_TARGET: "rpm"
    CI_DISTRO_TARGET: "centos8"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'


centos8:rpm:tagged-build:
  extends: .upload_pkg
  stage: packages
  needs: ["centos8:tagged-build-docker"]
  variables:
    MAKE_TARGET: "rpm"
    CI_DISTRO_TARGET: "centos8"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'
