include:
  - '.gitlab-ci-files/common-prepare.yml'

stages:
  - deps
  - build
  - build-docker
  - packages


# Debian

debian11:deps:
  extends: .make_in_docker
  stage: deps
  variables:
    MAKE_TARGET: "deps"
    CI_DISTRO_TARGET: "debian11"
    DEBIAN_FRONTEND: "noninteractive"
    BUILD: /build
    CARGO_HOME: /cargo
    CARGO_TARGET_DIR:
  rules:
    - changes:
        - DEPENDENCIES
        - scripts/ci/debian11/deps.pEpEngine.debian11.Dockerfile
        - scripts/ci/common/build_pEpEngine_deps.sh

debian11:build:
  tags:
    - linux
  stage: build
  image: ${DOCKER_REGISTRY_HOST}/pep-debian11-engine-deps:latest
  script:
    - cd scripts/ci/${CI_DISTRO_TARGET}
    - make ${MAKE_TARGET}
  variables:
    MAKE_TARGET: "build"
    CI_DISTRO_TARGET: "debian11"
    DEBIAN_FRONTEND: "noninteractive"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian11:tagged-build:
  tags:
    - linux
  stage: build
  image: ${DOCKER_REGISTRY_HOST}/pep-debian11-engine-deps:latest
  script:
    - cd scripts/ci/${CI_DISTRO_TARGET}
    - make ${MAKE_TARGET}
  variables:
    MAKE_TARGET: "build"
    CI_DISTRO_TARGET: "debian11"
    DEBIAN_FRONTEND: "noninteractive"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian11:build-docker:
  extends: .make_in_docker
  stage: build-docker
  needs: ["debian11:build"]
  variables:
    MAKE_TARGET: "build-docker"
    CI_DISTRO_TARGET: "debian11"
    DEBIAN_FRONTEND: "noninteractive"
  rules:
    - if: '$CI_COMMIT_TAG  !~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'

debian11:tagged-build-docker:
  extends: .make_in_docker
  stage: build-docker
  needs: ["debian11:tagged-build"]
  variables:
    MAKE_TARGET: "build-docker"
    CI_DISTRO_TARGET: "debian11"
    DEBIAN_FRONTEND: "noninteractive"
    TAGGED_BUILD: "true"
  rules:
    - if: '$CI_COMMIT_TAG  =~ /^Release_[0-9]+\.[0-9]+\.[0-9]+$/'
